version: '3.4'
services:
  web:
    container_name: web.api
    build:
      args:
        - APP_NAME=ApiMovimientos
        - NETCORE_VERSION=5.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - catalogdb
    restart: unless-stopped
  db:
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    volumes:
     - ./mongo_data/db:/data/db
  redis:
    container_name: rediscache
    restart: always    
    ports:
        - "6379:6379"    
