version: '3.4'
services:
  web:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: ./Dockerfile
  db:
    image: mongo
  redis:
    image: redis:alpine




